version: '3'

services:
  grafica:
    container_name: grafica
    image: ruby:2.6.5-buster
    working_dir: /app
    environment:
      DB_HOST: "neo4j:7474"
      TEST_DB_HOST: "neo4j-test:7475"
    volumes:
       - ./services/grafica:/app
       - v-grafica-gem:/usr/local/bundle
    ports:
      - 3000:3000
    tty: true
    command: /bin/bash
    depends_on:
      - grafica-neo4j
      - grafica-neo4j-test
  grafica-neo4j:
    container_name: neo4j
    image: neo4j:3.5.11
    volumes:
      - ./services/grafica/db/neo4j/conf:/var/lib/neo4j/conf
    ports:
      - '7474:7474'
      - '7687:7687'
  grafica-neo4j-test:
    container_name: neo4j-test
    image: neo4j:3.5.11
    volumes:
      - ./services/grafica/db/neo4j/conf-test:/var/lib/neo4j/conf
    ports:
      - '7475:7474'

volumes:
  v-grafica-gem:
